AI Bank Account Opening Fraud Detection

Data Preparation

This notebook prepares the Bank Account Fraud (BAF) dataset for Machine Learning and Deep Learning model training. The notebook performs the following tasks:

- Load the dataset
- Create a representative sample
- Explore the dataset
- Analyse the target variable
- Check missing values and duplicates
- Encode categorical variables
- Scale numerical features
- Create training and testing datasets
- Save the processed data for model training

Import Libraries

In [ ]:
from zipfile import ZipFile
import os

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

Load Dataset

In [ ]:
with ZipFile('/content/drive/MyDrive/PROYECT_4/archive.zip', 'r') as f:
  f.extractall('/content/drive/MyDrive/PROYECT_4/data')

In [ ]:
os.listdir('/content/drive/MyDrive/PROYECT_4/data')

['Base.csv',
 'Variant I.csv',
 'Variant II.csv',
 'Variant III.csv',
 'Variant IV.csv',
 'Variant V.csv']

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/PROYECT_4/data/Base.csv')

Exploratory Data Analysis

In [ ]:
pd.set_option('display.max_columns', None)

In [ ]:
df.head()

,fraud_bool,income,name_email_similarity,prev_address_months_count,current_address_months_count,customer_age,days_since_request,intended_balcon_amount,payment_type,zip_count_4w,velocity_6h,velocity_24h,velocity_4w,bank_branch_count_8w,date_of_birth_distinct_emails_4w,employment_status,credit_risk_score,email_is_free,housing_status,phone_home_valid,phone_mobile_valid,bank_months_count,has_other_cards,proposed_credit_limit,foreign_request,source,session_length_in_minutes,device_os,keep_alive_session,device_distinct_emails_8w,device_fraud_count,month
0,0,0.3,0.986506,-1,25,40,0.006735,102.453711,AA,1059,13096.035018,7850.955007,6742.080561,5,5,CB,163,1,BC,0,1,9,0,1500.0,0,INTERNET,16.224843,linux,1,1,0,0
1,0,0.8,0.617426,-1,89,20,0.010095,-0.849551,AD,1658,9223.283431,5745.251481,5941.664859,3,18,CA,154,1,BC,1,1,2,0,1500.0,0,INTERNET,3.363854,other,1,1,0,0
2,0,0.8,0.996707,9,14,40,0.012316,-1.490386,AB,1095,4471.472149,5471.988958,5992.555113,15,11,CA,89,1,BC,0,1,30,0,200.0,0,INTERNET,22.730559,windows,0,1,0,0
3,0,0.6,0.475100,11,14,30,0.006991,-1.863101,AB,3483,14431.993621,6755.344479,5970.336831,11,13,CA,90,1,BC,0,1,1,0,200.0,0,INTERNET,15.215816,linux,1,1,0,0
4,0,0.9,0.842307,-1,29,40,5.742626,47.152498,AA,2339,7601.511579,5124.046930,5940.734212,1,6,CA,91,0,BC,1,1,26,0,200.0,0,INTERNET,3.743048,other,0,1,0,0

In [ ]:
df.shape

(1000000, 32)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 32 columns):
 #   Column                            Non-Null Count    Dtype
---  ------                            --------------    -----
 0   fraud_bool                        1000000 non-null  int64
 1   income                            1000000 non-null  float64
 2   name_email_similarity             1000000 non-null  float64
 3   prev_address_months_count         1000000 non-null  int64
 4   current_address_months_count      1000000 non-null  int64
 5   customer_age                      1000000 non-null  int64
 6   days_since_request                1000000 non-null  float64
 7   intended_balcon_amount            1000000 non-null  float64
 8   payment_type                      1000000 non-null  object
 9   zip_count_4w                      1000000 non-null  int64
 10  velocity_6h                       1000000 non-null  float64
 11  velocity_24h                      1000000 non-null  float64
 12  velocity_4w                       1000000 non-null  float64
 13  bank_branch_count_8w              1000000 non-null  int64
 14  date_of_birth_distinct_emails_4w  1000000 non-null  int64
 15  employment_status                 1000000 non-null  object
 16  credit_risk_score                 1000000 non-null  int64
 17  email_is_free                     1000000 non-null  int64
 18  housing_status                    1000000 non-null  object
 19  phone_home_valid                  1000000 non-null  int64
 20  phone_mobile_valid                1000000 non-null  int64
 21  bank_months_count                 1000000 non-null  int64
 22  has_other_cards                   1000000 non-null  int64
 23  proposed_credit_limit             1000000 non-null  float64
 24  foreign_request                   1000000 non-null  int64
 25  source                            1000000 non-null  object
 26  session_length_in_minutes         1000000 non-null  float64
 27  device_os                         1000000 non-null  object
 28  keep_alive_session                1000000 non-null  int64
 29  device_distinct_emails_8w         1000000 non-null  int64
 30  device_fraud_count                1000000 non-null  int64
 31  month                             1000000 non-null  int64
dtypes: float64(9), int64(18), object(5)
memory usage: 244.1+ MB

In [ ]:
df.isnull().sum()

fraud_bool                          0
income                              0
name_email_similarity               0
prev_address_months_count           0
current_address_months_count        0
customer_age                        0
days_since_request                  0
intended_balcon_amount              0
payment_type                        0
zip_count_4w                        0
velocity_6h                         0
velocity_24h                        0
velocity_4w                         0
bank_branch_count_8w                0
date_of_birth_distinct_emails_4w    0
employment_status                   0
credit_risk_score                   0
email_is_free                       0
housing_status                      0
phone_home_valid                    0
phone_mobile_valid                  0
bank_months_count                   0
has_other_cards                     0
proposed_credit_limit               0
foreign_request                     0
source                              0
session_length_in_minutes           0
device_os                           0
keep_alive_session                  0
device_distinct_emails_8w           0
device_fraud_count                  0
month                               0
dtype: int64

In [ ]:
df.describe()

,fraud_bool,income,name_email_similarity,prev_address_months_count,current_address_months_count,customer_age,days_since_request,intended_balcon_amount,zip_count_4w,velocity_6h,velocity_24h,velocity_4w,bank_branch_count_8w,date_of_birth_distinct_emails_4w,credit_risk_score,email_is_free,phone_home_valid,phone_mobile_valid,bank_months_count,has_other_cards,proposed_credit_limit,foreign_request,session_length_in_minutes,keep_alive_session,device_distinct_emails_8w,device_fraud_count,month
count,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1.000000e+06,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.0,1000000.000000
mean,0.011029,0.562696,0.493694,16.718568,86.587867,33.689080,1.025705e+00,8.661499,1572.692049,5665.296605,4769.781965,4856.324016,184.361849,9.503544,130.989595,0.529886,0.417077,0.889676,10.839303,0.222988,515.851010,0.025242,7.544940,0.576947,1.018312,0.0,3.288674
std,0.104438,0.290343,0.289125,44.046230,88.406599,12.025799,5.381835e+00,20.236155,1005.374565,3009.380665,1479.212612,919.843934,459.625329,5.033792,69.681812,0.499106,0.493076,0.313293,12.116875,0.416251,487.559902,0.156859,8.033106,0.494044,0.180761,0.0,2.209994
min,0.000000,0.100000,0.000001,-1.000000,-1.000000,10.000000,4.036860e-09,-15.530555,1.000000,-170.603072,1300.307314,2825.748405,0.000000,0.000000,-170.000000,0.000000,0.000000,0.000000,-1.000000,0.000000,190.000000,0.000000,-1.000000,0.000000,-1.000000,0.0,0.000000
25%,0.000000,0.300000,0.225216,-1.000000,19.000000,20.000000,7.193246e-03,-1.181488,894.000000,3436.365848,3593.179135,4268.368423,1.000000,6.000000,83.000000,0.000000,0.000000,1.000000,-1.000000,0.000000,200.000000,0.000000,3.103053,0.000000,1.000000,0.0,1.000000
50%,0.000000,0.600000,0.492153,-1.000000,52.000000,30.000000,1.517574e-02,-0.830507,1263.000000,5319.769349,4749.921161,4913.436941,9.000000,9.000000,122.000000,1.000000,0.000000,1.000000,5.000000,0.000000,200.000000,0.000000,5.114321,1.000000,1.000000,0.0,3.000000
75%,0.000000,0.800000,0.755567,12.000000,130.000000,40.000000,2.633069e-02,4.984176,1944.000000,7680.717827,5752.574191,5488.083356,25.000000,13.000000,178.000000,1.000000,1.000000,1.000000,25.000000,0.000000,500.000000,0.000000,8.866131,1.000000,1.000000,0.0,5.000000
max,1.000000,0.900000,0.999999,383.000000,428.000000,90.000000,7.845690e+01,112.956928,6700.000000,16715.565404,9506.896596,6994.764201,2385.000000,39.000000,389.000000,1.000000,1.000000,1.000000,32.000000,1.000000,2100.000000,1.000000,85.899143,1.000000,2.000000,0.0,7.000000

In [ ]:
df.columns

Index(['fraud_bool', 'income', 'name_email_similarity',
       'prev_address_months_count', 'current_address_months_count',
       'customer_age', 'days_since_request', 'intended_balcon_amount',
       'payment_type', 'zip_count_4w', 'velocity_6h', 'velocity_24h',
       'velocity_4w', 'bank_branch_count_8w',
       'date_of_birth_distinct_emails_4w', 'employment_status',
       'credit_risk_score', 'email_is_free', 'housing_status',
       'phone_home_valid', 'phone_mobile_valid', 'bank_months_count',
       'has_other_cards', 'proposed_credit_limit', 'foreign_request', 'source',
       'session_length_in_minutes', 'device_os', 'keep_alive_session',
       'device_distinct_emails_8w', 'device_fraud_count', 'month'],
      dtype='object')

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
categorical = df.select_dtypes(include='object').columns
categorical

Index(['payment_type', 'employment_status', 'housing_status', 'source',
       'device_os'],
      dtype='object')

In [ ]:
numerical = df.select_dtypes(exclude='object').columns
numerical

Index(['fraud_bool', 'income', 'name_email_similarity',
       'prev_address_months_count', 'current_address_months_count',
       'customer_age', 'days_since_request', 'intended_balcon_amount',
       'zip_count_4w', 'velocity_6h', 'velocity_24h', 'velocity_4w',
       'bank_branch_count_8w', 'date_of_birth_distinct_emails_4w',
       'credit_risk_score', 'email_is_free', 'phone_home_valid',
       'phone_mobile_valid', 'bank_months_count', 'has_other_cards',
       'proposed_credit_limit', 'foreign_request', 'session_length_in_minutes',
       'keep_alive_session', 'device_distinct_emails_8w', 'device_fraud_count',
       'month'],
      dtype='object')

In [ ]:
for col in categorical:
  print('\n')
  print(df[col].value_counts())

payment_type
AB    370554
AA    258249
AC    252071
AD    118837
AE       289
Name: count, dtype: int64


employment_status
CA    730252
CB    138288
CF     44034
CC     37758
CD     26522
CE     22693
CG       453
Name: count, dtype: int64


housing_status
BC    372143
BB    260965
BA    169675
BE    169135
BD     26161
BF      1669
BG       252
Name: count, dtype: int64


source
INTERNET    992952
TELEAPP       7048
Name: count, dtype: int64


device_os
other        342728
linux        332712
windows      263506
macintosh     53826
x11            7228
Name: count, dtype: int64

In [ ]:
for col in numerical:
  print('\n')
  print(df[col].value_counts())

fraud_bool
0    988971
1     11029
Name: count, dtype: int64


income
0.9    221419
0.1    157449
0.8    146650
0.6    111973
0.7    105109
0.4     81364
0.2     69345
0.5     55858
0.3     50833
Name: count, dtype: int64


name_email_similarity
0.849078    2
0.087839    2
0.670345    2
0.012690    2
0.621812    2
           ..
0.794049    1
0.813372    1
0.895561    1
0.422189    1
0.693804    1
Name: count, Length: 998861, dtype: int64


prev_address_months_count
-1      712920
 11      11475
 28      10275
 29      10150
 10      10082
         ...
 374         1
 5           1
 375         1
 383         1
 381         1
Name: count, Length: 374, dtype: int64


current_address_months_count
6      16376
7      16270
8      16089
5      15896
9      15688
       ...
419        1
417        1
409        1
414        1
428        1
Name: count, Length: 423, dtype: int64


customer_age
30    311433
20    245855
40    238712
50    140353
60     34770
10     20987
70      6517
80      1297
90        76
Name: count, dtype: int64


days_since_request
0.010164    3
0.016688    3
0.018549    3
0.019022    3
0.029560    3
           ..
0.026679    1
0.005904    1
0.021494    1
0.028969    1
0.011639    1
Name: count, Length: 989330, dtype: int64


intended_balcon_amount
-0.702732    3
-1.433400    3
-0.573660    3
-0.678029    3
-1.125846    3
            ..
-0.688216    1
-0.278312    1
-1.438301    1
-1.219036    1
-0.541690    1
Name: count, Length: 994971, dtype: int64


zip_count_4w
1020    798
1062    782
1042    770
969     767
1026    763
       ...
6268      1
6349      1
6388      1
6281      1
6451      1
Name: count, Length: 6306, dtype: int64


velocity_6h
4144.024168     2
5215.020203     2
11137.542629    2
2212.625812     2
767.647100      2
               ..
5206.534093     1
6942.079500     1
10184.257135    1
8302.564596     1
8968.902274     1
Name: count, Length: 998687, dtype: int64


velocity_24h
4667.863854    3
3906.416302    3
5082.326632    3
6676.201310    3
4754.238036    2
              ..
4971.010987    1
3278.328802    1
6189.289001    1
7656.865926    1
5119.829026    1
Name: count, Length: 998940, dtype: int64


velocity_4w
5466.870949    3
4297.664858    3
4721.171021    2
4888.096234    2
4763.769048    2
              ..
5403.587061    1
5733.693226    1
5576.453881    1
5492.817226    1
5485.222125    1
Name: count, Length: 998318, dtype: int64


bank_branch_count_8w
1       149028
0       144376
2        57792
11       31160
10       30694
         ...
2342         1
2385         1
2367         1
2347         1
2332         1
Name: count, Length: 2326, dtype: int64


date_of_birth_distinct_emails_4w
7     83193
5     80799
8     79491
6     78225
11    73456
9     67341
10    62681
4     62549
13    60773
12    52409
3     44227
15    43200
14    39927
2     35717
16    25628
18    21081
17    20017
19    16453
1     14377
20    10237
21     6762
22     5599
23     4788
24     3476
25     2155
0      1336
26     1212
27      706
28      527
29      455
30      383
31      273
32      223
33      142
34       85
35       49
36       31
37       12
38        3
39        2
Name: count, dtype: int64


credit_risk_score
 113    6791
 116    6784
 110    6774
 115    6734
 117    6717
        ...
 387       1
-165       1
-153       1
-170       1
 383       1
Name: count, Length: 551, dtype: int64


email_is_free
1    529886
0    470114
Name: count, dtype: int64


phone_home_valid
0    582923
1    417077
Name: count, dtype: int64


phone_mobile_valid
1    889676
0    110324
Name: count, dtype: int64


bank_months_count
-1     253635
 1     194802
 28     80082
 15     59141
 30     50777
 31     46084
 25     40450
 10     37158
 20     30850
 21     29098
 5      28001
 2      25836
 26     24779
 11     23745
 6      17678
 29     11696
 3       8580
 19      8212
 22      6741
 9       4801
 16      4563
 27      4197
 4       3834
 24      1822
 12      1121
 7        931
 14       493
 18       491
 23       320
 32        46
 8         30
 17         4
 13         2
Name: count, dtype: int64


has_other_cards
0    777012
1    222988
Name: count, dtype: int64


proposed_credit_limit
200.0     613854
1500.0    145735
500.0     135797
1000.0     81882
990.0       7580
510.0       6967
2000.0      6114
490.0        870
210.0        607
1900.0       390
190.0        163
2100.0        41
Name: count, dtype: int64


foreign_request
0    974758
1     25242
Name: count, dtype: int64


session_length_in_minutes
-1.000000    2015
 4.192392       3
 7.960109       3
 9.661989       3
 5.323466       3
             ...
 1.938174       1
 3.193973       1
 8.349347       1
 2.702277       1
 4.147696       1
Name: count, Length: 994887, dtype: int64


keep_alive_session
1    576947
0    423053
Name: count, dtype: int64


device_distinct_emails_8w
 1    968067
 2     25302
 0      6272
-1       359
Name: count, dtype: int64


device_fraud_count
0    1000000
Name: count, dtype: int64


month
3    150936
2    136979
0    132440
4    127691
1    127620
5    119323
6    108168
7     96843
Name: count, dtype: int64

In [ ]:
from sklearn.preprocessing import StandardScaler, LabelEncoder
import joblib

In [ ]:
df = df.groupby('fraud_bool', group_keys=False).apply(lambda x: x.sample(frac=200000 / len(df),random_state=42)).reset_index(drop=True)

/tmp/ipykernel_4726/2535913794.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df = df.groupby('fraud_bool', group_keys=False).apply(lambda x: x.sample(frac=200000 / len(df),random_state=42)).reset_index(drop=True)

In [ ]:
df.shape

(200000, 32)

In [ ]:
df['fraud_bool'].value_counts()

fraud_bool
0    197794
1      2206
Name: count, dtype: int64

In [ ]:
round(df['fraud_bool'].value_counts(normalize=True) * 100, 2)

fraud_bool
0    98.9
1     1.1
Name: proportion, dtype: float64

In [ ]:
df.isnull().sum().sum()

np.int64(0)

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
encoder = LabelEncoder()

In [ ]:
encoders = {}
for col in categorical:
  df[col] = encoder.fit_transform(df[col])
  encoders[col] = encoder

In [ ]:
df.head()

,fraud_bool,income,name_email_similarity,prev_address_months_count,current_address_months_count,customer_age,days_since_request,intended_balcon_amount,payment_type,zip_count_4w,velocity_6h,velocity_24h,velocity_4w,bank_branch_count_8w,date_of_birth_distinct_emails_4w,employment_status,credit_risk_score,email_is_free,housing_status,phone_home_valid,phone_mobile_valid,bank_months_count,has_other_cards,proposed_credit_limit,foreign_request,source,session_length_in_minutes,device_os,keep_alive_session,device_distinct_emails_8w,device_fraud_count,month
0,0,0.8,0.735925,104,10,30,0.030076,-1.480613,1,2062,1664.244920,3839.597315,4962.294552,45,14,0,91,1,1,0,1,1,0,200.0,0,0,3.742273,2,1,1,0,3
1,0,0.9,0.313330,-1,30,30,0.002789,-1.303670,1,1498,7375.041588,5404.494837,5072.988221,25,11,0,73,0,2,0,1,1,0,200.0,0,0,3.669544,2,1,1,0,4
2,0,0.1,0.129044,-1,238,20,0.013602,-1.027149,1,1019,11545.580597,7142.127074,5767.843283,6,10,0,47,0,4,1,1,30,0,200.0,0,0,3.411296,0,1,1,0,2
3,0,0.9,0.071233,-1,65,30,0.005794,-0.877066,3,1140,2928.116344,4557.353802,5638.310004,2021,9,1,77,1,2,0,1,1,1,200.0,0,0,5.310112,0,1,1,0,2
4,0,0.1,0.920019,62,13,30,0.018723,50.296179,0,1103,3721.656126,2703.314684,4359.495202,2,4,0,185,1,1,1,0,-1,0,1500.0,0,0,20.368814,0,1,1,0,4

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 32 columns):
 #   Column                            Non-Null Count   Dtype
---  ------                            --------------   -----
 0   fraud_bool                        200000 non-null  int64
 1   income                            200000 non-null  float64
 2   name_email_similarity             200000 non-null  float64
 3   prev_address_months_count         200000 non-null  int64
 4   current_address_months_count      200000 non-null  int64
 5   customer_age                      200000 non-null  int64
 6   days_since_request                200000 non-null  float64
 7   intended_balcon_amount            200000 non-null  float64
 8   payment_type                      200000 non-null  int64
 9   zip_count_4w                      200000 non-null  int64
 10  velocity_6h                       200000 non-null  float64
 11  velocity_24h                      200000 non-null  float64
 12  velocity_4w                       200000 non-null  float64
 13  bank_branch_count_8w              200000 non-null  int64
 14  date_of_birth_distinct_emails_4w  200000 non-null  int64
 15  employment_status                 200000 non-null  int64
 16  credit_risk_score                 200000 non-null  int64
 17  email_is_free                     200000 non-null  int64
 18  housing_status                    200000 non-null  int64
 19  phone_home_valid                  200000 non-null  int64
 20  phone_mobile_valid                200000 non-null  int64
 21  bank_months_count                 200000 non-null  int64
 22  has_other_cards                   200000 non-null  int64
 23  proposed_credit_limit             200000 non-null  float64
 24  foreign_request                   200000 non-null  int64
 25  source                            200000 non-null  int64
 26  session_length_in_minutes         200000 non-null  float64
 27  device_os                         200000 non-null  int64
 28  keep_alive_session                200000 non-null  int64
 29  device_distinct_emails_8w         200000 non-null  int64
 30  device_fraud_count                200000 non-null  int64
 31  month                             200000 non-null  int64
dtypes: float64(9), int64(23)
memory usage: 48.8 MB

Target and Split Data

In [ ]:
X = df.drop('fraud_bool', axis=1)
y = df['fraud_bool']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [ ]:
print(X.shape, X_train.shape, X_test.shape)
print(y.shape, y_train.shape, y_test.shape)

(200000, 31) (160000, 31) (40000, 31)
(200000,) (160000,) (40000,)

In [ ]:
scaler = StandardScaler()

In [ ]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:
os.makedirs('/content/drive/MyDrive/PROYECT_4/data/processed', exist_ok=True)

In [ ]:
joblib.dump(X_train, '/content/drive/MyDrive/PROYECT_4/data/processed/X_train.pkl')
joblib.dump(X_test, '/content/drive/MyDrive/PROYECT_4/data/processed/X_test.pkl')

joblib.dump(X_train_scaled, '/content/drive/MyDrive/PROYECT_4/data/processed/X_train_scaled.pkl')
joblib.dump(X_test_scaled, '/content/drive/MyDrive/PROYECT_4/data/processed/X_test_scaled.pkl')

joblib.dump(y_train, '/content/drive/MyDrive/PROYECT_4/data/processed/y_train.pkl')
joblib.dump(y_test, '/content/drive/MyDrive/PROYECT_4/data/processed/y_test.pkl')

joblib.dump(encoders, '/content/drive/MyDrive/PROYECT_4/data/processed/encoders.pkl')
joblib.dump(scaler, '/content/drive/MyDrive/PROYECT_4/data/processed/scaler.pkl')

['/content/drive/MyDrive/PROYECT_4/data/processed/scaler.pkl']

The Bank Account Fraud (BAF) dataset was successfully prepared for Machine Learning and Deep Learning model training.

The following tasks were completed:

- Loaded the original BAF dataset
- Created a representative sample of 200,000 applications while preserving the original class distribution
- Explored the dataset structure and target variable
- Verified that the dataset contains no missing values or duplicate records
- Encoded all categorical variables using Label Encoding
- Split the dataset into training and testing sets using stratified sampling
- Standardised the numerical features for Deep Learning models
- Saved the processed datasets, scaler and label encoders for the model training phase

The dataset is now ready for training and comparing multiple Machine Learning and Deep Learning models.